# Username to make admin API requests
# Default: 'admin'
admin_username: 'admin'

# Plaintext password to make admin API requests
# Safe to remove if admin_hashed_password is set
# Default: unset
admin_password: 'password'

# Hashed password (bcrypt) to make admin API requests - Preferred over plaintext, use securepass.sh to generate
# Please note that authentication takes noticeably longer than using plaintext password
# Don't include the <username>: segment, just the hash
# Default: '$2y$15$Dhll3IY42R.JNOYazarlG.8IndwMjxmHLpFsebJzcGTJd.gbsAwna' (hash for 'password')
#admin_hashed_password: '$2y$15$Dhll3IY42R.JNOYazarlG.8IndwMjxmHLpFsebJzcGTJd.gbsAwna'

# Filename of the URL database
# Default: 'urls'
database_name: 'urls'

# Length of random short URLs by default
# Default: 4
random_length: 4

# Allowed URL characters
# Default: ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-_
allowed_chars: 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-_'

# Amount of time in seconds to spend generating random short URLs until timeout
# Default: 5
random_gen_timeout: 5

# Name shown on tab while on site and on page header
# Default: 'liteshort'
site_name: 'liteshort'

# URL shown when finished generating shortlinks. Include the / at the end.
# If not set, it is automatically taken from the URL the shorten request is sent to.
# Default: unset
site_url: